
import java.awt.Point;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nicolas
 */
public class StormFrame extends javax.swing.JFrame {
    
    Storm storm = null;
    Timer timer = null;
    Point mouse = null;

    /**
     * Creates new form StormFrame
     */
    public StormFrame() {
        initComponents();
        
        setTitle("Storm");
        
        storm = new Storm();
        stormPanel.setStorm(storm);
        
        timer = new Timer(500, event -> {
            stormPanel.repaint();
        });
        timer.start();
    }
    
    private int getRandomInteger(int min, int max) {
        return (int) (Math.random() * (max - min + 1)) + min;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stormPanel = new StormPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stormPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                stormPanelMouseDragged(evt);
            }
        });
        stormPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stormPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stormPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout stormPanelLayout = new javax.swing.GroupLayout(stormPanel);
        stormPanel.setLayout(stormPanelLayout);
        stormPanelLayout.setHorizontalGroup(
            stormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        stormPanelLayout.setVerticalGroup(
            stormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stormPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stormPanelMousePressed
        mouse = evt.getPoint();
        int radius = 0;
        storm.add(new Snowflake(getRandomInteger(2, 5), mouse, radius));
        stormPanel.repaint();
    }//GEN-LAST:event_stormPanelMousePressed

    private void stormPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stormPanelMouseReleased
        
    }//GEN-LAST:event_stormPanelMouseReleased

    private void stormPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stormPanelMouseDragged
        Point mouse2 = evt.getPoint();
        int radius = (int) (Math.sqrt(Math.pow(mouse2.x - mouse.x, 2) + Math.pow(mouse2.y - mouse.y, 2)));
        storm.getLast().setDiameter(radius * 2);
        stormPanel.repaint();
    }//GEN-LAST:event_stormPanelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StormFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private StormPanel stormPanel;
    // End of variables declaration//GEN-END:variables
}
