package ui;


import model.Line;
import model.Elements;
import model.Element;
import model.Rectangle;
import model.Ellipse;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nicolas
 */
public class MainFrame extends javax.swing.JFrame {
    
    private Elements elements = null;
    
    private boolean drawNextLine = false;
    private boolean drawNextRectangle = false;
    private boolean drawNextEllipse = false;
    
    private Line line = null;
    private Rectangle rectangle = null;
    private Ellipse ellipse = null;
    
    private Color outlineColor = Color.BLACK;
    private Color fillColor = Color.BLACK;
    
    private Point dragStart = null;
    private Point elementDragStart = null;
    private Point elementDragEnd = null;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Fake Illustrator");
        elements = new Elements();
        drawPanel.setElements(elements);
        outlineColorMenuItem.setForeground(outlineColor);
        fillColorMenuItem.setForeground(fillColor);
        
        mouseCheckBoxMenuItem.setSelected(true);
        lineCheckBoxMenuItem.setSelected(false);
        rectangleCheckBoxMenuItem.setSelected(false);
        ellipseCheckBoxMenuItem.setSelected(false);

        updateView();
    }
    
    public void updateView() {
        drawPanel.repaint();
        
        boolean hasSelection = elements.getSelectedElement() != null;
        deleteMenuItem.setEnabled(hasSelection);
        bringForwardMenuItem.setEnabled(hasSelection);
        sendBackwardMenuItem.setEnabled(hasSelection);
        bringToFrontMenuItem.setEnabled(hasSelection);
        sendToBackMenuItem.setEnabled(hasSelection);
        
        clearMenuItem.setEnabled(!elements.isEmpty());
        saveMenuItem.setEnabled(!elements.isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        drawPanel = new ui.DrawPanel();
        illustratorMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        loadMenuItem = new javax.swing.JMenuItem();
        shapesMenu = new javax.swing.JMenu();
        mouseCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        lineCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        rectangleCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        ellipseCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        elementMenu = new javax.swing.JMenu();
        outlineColorMenuItem = new javax.swing.JMenuItem();
        fillColorMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        clearMenuItem = new javax.swing.JMenuItem();
        layersMenu = new javax.swing.JMenu();
        bringForwardMenuItem = new javax.swing.JMenuItem();
        bringToFrontMenuItem = new javax.swing.JMenuItem();
        sendBackwardMenuItem = new javax.swing.JMenuItem();
        sendToBackMenuItem = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drawPanelMouseDragged(evt);
            }
        });
        drawPanel.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                drawPanelMouseWheelMoved(evt);
            }
        });
        drawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                drawPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveMenuItem.setText("Save to JSON");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        loadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        loadMenuItem.setText("Load from JSON");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadMenuItem);

        illustratorMenuBar.add(fileMenu);

        shapesMenu.setText("Shapes");

        mouseCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        mouseCheckBoxMenuItem.setSelected(true);
        mouseCheckBoxMenuItem.setText("Mouse");
        mouseCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseCheckBoxMenuItemActionPerformed(evt);
            }
        });
        shapesMenu.add(mouseCheckBoxMenuItem);

        lineCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        lineCheckBoxMenuItem.setText("Line");
        lineCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineCheckBoxMenuItemActionPerformed(evt);
            }
        });
        shapesMenu.add(lineCheckBoxMenuItem);

        rectangleCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        rectangleCheckBoxMenuItem.setSelected(true);
        rectangleCheckBoxMenuItem.setText("Rectangle");
        rectangleCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleCheckBoxMenuItemActionPerformed(evt);
            }
        });
        shapesMenu.add(rectangleCheckBoxMenuItem);

        ellipseCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        ellipseCheckBoxMenuItem.setSelected(true);
        ellipseCheckBoxMenuItem.setText("Ellipse");
        ellipseCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ellipseCheckBoxMenuItemActionPerformed(evt);
            }
        });
        shapesMenu.add(ellipseCheckBoxMenuItem);

        illustratorMenuBar.add(shapesMenu);

        elementMenu.setText("Element");

        outlineColorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        outlineColorMenuItem.setText("Change outline color");
        outlineColorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outlineColorMenuItemActionPerformed(evt);
            }
        });
        elementMenu.add(outlineColorMenuItem);

        fillColorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, 0));
        fillColorMenuItem.setText("Change fill color");
        fillColorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorMenuItemActionPerformed(evt);
            }
        });
        elementMenu.add(fillColorMenuItem);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        deleteMenuItem.setText("Delete");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        elementMenu.add(deleteMenuItem);

        clearMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        clearMenuItem.setText("Clear");
        clearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuItemActionPerformed(evt);
            }
        });
        elementMenu.add(clearMenuItem);

        illustratorMenuBar.add(elementMenu);

        layersMenu.setText("Layers");

        bringForwardMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, 0));
        bringForwardMenuItem.setText("Bring forward");
        bringForwardMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bringForwardMenuItemActionPerformed(evt);
            }
        });
        layersMenu.add(bringForwardMenuItem);

        bringToFrontMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        bringToFrontMenuItem.setText("Bring to front");
        bringToFrontMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bringToFrontMenuItemActionPerformed(evt);
            }
        });
        layersMenu.add(bringToFrontMenuItem);

        sendBackwardMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, 0));
        sendBackwardMenuItem.setText("Send backward");
        sendBackwardMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBackwardMenuItemActionPerformed(evt);
            }
        });
        layersMenu.add(sendBackwardMenuItem);

        sendToBackMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        sendToBackMenuItem.setText("Send to back");
        sendToBackMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToBackMenuItemActionPerformed(evt);
            }
        });
        layersMenu.add(sendToBackMenuItem);

        illustratorMenuBar.add(layersMenu);

        setJMenuBar(illustratorMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMousePressed
        Point start = evt.getPoint();
        if (drawNextLine) {
            line = new Line(start, start, outlineColor, fillColor);
            elements.add(line);
        } else if (drawNextRectangle) {
            rectangle = new Rectangle(start, start, outlineColor, fillColor);
            elements.add(rectangle);
        } else if (drawNextEllipse) {
            ellipse = new Ellipse(start, start, outlineColor, fillColor);
            elements.add(ellipse);
        } else {
            elements.selectElementAt(start);
            Element selcted = elements.getSelectedElement();
            if (selcted != null) {
                dragStart = start;
                elementDragStart = new Point(selcted.getStart());
                elementDragEnd = new Point(selcted.getEnd());
            }
        }
        updateView();
    }//GEN-LAST:event_drawPanelMousePressed

    private void drawPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseReleased
        Point end = evt.getPoint();
        if (line != null && drawNextLine) {
            line.setEnd(end);
        } else if (rectangle != null && drawNextRectangle) {
            rectangle.setEnd(end);
        } else if (ellipse != null && drawNextEllipse) {
            ellipse.setEnd(end);
        }
        dragStart = null;
        elementDragStart = null;
        elementDragEnd = null;
        updateView();
    }//GEN-LAST:event_drawPanelMouseReleased

    private void drawPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseDragged
        Point end = evt.getPoint();
        if (line != null && drawNextLine) {
            line.setEnd(end);
        } else if (rectangle != null && drawNextRectangle) {
            rectangle.setEnd(end);
        } else if (ellipse != null && drawNextEllipse) {
            ellipse.setEnd(end);
        } else if (dragStart != null && elements.getSelectedElement() != null) {
            Element selected = elements.getSelectedElement();
            int dx = end.x - dragStart.x;
            int dy = end.y - dragStart.y;   
            selected.setStart(new Point(elementDragStart.x + dx, elementDragStart.y + dy));
            selected.setEnd(new Point(elementDragEnd.x + dx, elementDragEnd.y + dy));
        }
        updateView();
    }//GEN-LAST:event_drawPanelMouseDragged

    private void drawPanelMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_drawPanelMouseWheelMoved
        Element selected = elements.getSelectedElement();
        if (selected != null) {
            int centerX = (selected.getStart().x + selected.getEnd().x) / 2;
            int centerY = (selected.getStart().y + selected.getEnd().y) / 2;
            Point center = new Point(centerX, centerY);
            
            if (evt.getWheelRotation() < 0) {
                // Scroll UP --> SCALE UP
                selected.scale(1.1, center);
            } else if (evt.getWheelRotation() > 0) {
                // Scroll DOWN --> SCALE DOWN
                selected.scale(0.9, center);
            }
            updateView();
        }
    }//GEN-LAST:event_drawPanelMouseWheelMoved

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        File workingDirectory = new File(System.getProperty("user.dir"));
        fileChooser.setCurrentDirectory(workingDirectory);
        fileChooser.setFileFilter(new FileNameExtensionFilter("JSON Files", "json"));
        fileChooser.setDialogTitle("Save file ...");
        int returnVal = fileChooser.showSaveDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String fileName = fileChooser.getSelectedFile().getAbsolutePath();
            if (!fileName.toLowerCase().endsWith(".json")) {
                fileName += ".json";
            }
            try {
                elements.saveToJSON(fileName);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        File workingDirectory = new File(System.getProperty("user.dir"));
        fileChooser.setCurrentDirectory(workingDirectory);
        fileChooser.setFileFilter(new FileNameExtensionFilter("JSON Files", "json"));
        fileChooser.setDialogTitle("Open file ...");
        int returnVal = fileChooser.showOpenDialog(this);
         
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String fileName = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                elements.loadFromJSON(fileName);
                updateView();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void outlineColorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outlineColorMenuItemActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Outline Color", outlineColor);
        if (newColor != null) {
            Element selected = elements.getSelectedElement();
            if (selected != null) {
                selected.setOutlineColor(newColor);
            } else {
                outlineColor = newColor;
                outlineColorMenuItem.setForeground(newColor);
            }
            updateView();
        }
    }//GEN-LAST:event_outlineColorMenuItemActionPerformed

    private void fillColorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorMenuItemActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Outline Color", fillColor);
        if (newColor != null) {
            Element selected = elements.getSelectedElement();
            if (selected != null) {
                selected.setFillColor(newColor);
            } else {
                fillColor = newColor;
                fillColorMenuItem.setForeground(newColor);
            }
            updateView();
        }
    }//GEN-LAST:event_fillColorMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        elements.removeSelected();
        updateView();
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void clearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuItemActionPerformed
        elements.clear();
        updateView();
    }//GEN-LAST:event_clearMenuItemActionPerformed

    private void bringForwardMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bringForwardMenuItemActionPerformed
        Element selected = elements.getSelectedElement();
        if (selected != null) {
            elements.bringForward(selected);
            updateView();
        }
    }//GEN-LAST:event_bringForwardMenuItemActionPerformed

    private void bringToFrontMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bringToFrontMenuItemActionPerformed
        Element selected = elements.getSelectedElement();
        if (selected != null) {
            elements.bringToFront(selected);
            updateView();
        }
    }//GEN-LAST:event_bringToFrontMenuItemActionPerformed

    private void sendBackwardMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBackwardMenuItemActionPerformed
        Element selected = elements.getSelectedElement();
        if (selected != null) {
            elements.sendBackward(selected);
            updateView();
        }
    }//GEN-LAST:event_sendBackwardMenuItemActionPerformed

    private void sendToBackMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToBackMenuItemActionPerformed
        Element selected = elements.getSelectedElement();
        if (selected != null) {
            elements.sendToBack(selected);
            updateView();
        }
    }//GEN-LAST:event_sendToBackMenuItemActionPerformed

    private void mouseCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseCheckBoxMenuItemActionPerformed
        mouseCheckBoxMenuItem.setSelected(true);
        drawNextLine = false;
        lineCheckBoxMenuItem.setSelected(false);
        drawNextRectangle = false;
        rectangleCheckBoxMenuItem.setSelected(false);
        drawNextEllipse = false;
        ellipseCheckBoxMenuItem.setSelected(false);
//        System.out.println(drawNextLine + " " + drawNextRectangle + " " + drawNextEllipse);
    }//GEN-LAST:event_mouseCheckBoxMenuItemActionPerformed

    private void lineCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineCheckBoxMenuItemActionPerformed
        if (lineCheckBoxMenuItem.isSelected()) {
            mouseCheckBoxMenuItem.setSelected(false);
            drawNextLine = true;
            lineCheckBoxMenuItem.setSelected(true);
            drawNextRectangle = false;
            rectangleCheckBoxMenuItem.setSelected(false);
            drawNextEllipse = false;
            ellipseCheckBoxMenuItem.setSelected(false);
        } else {
            drawNextLine = !drawNextLine;
            mouseCheckBoxMenuItem.setSelected(true);
        }
//        System.out.println(drawNextLine + " " + drawNextRectangle + " " + drawNextEllipse);
    }//GEN-LAST:event_lineCheckBoxMenuItemActionPerformed

    private void rectangleCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleCheckBoxMenuItemActionPerformed
        if (rectangleCheckBoxMenuItem.isSelected()) {
            mouseCheckBoxMenuItem.setSelected(false);
            drawNextLine = false;
            lineCheckBoxMenuItem.setSelected(false);
            drawNextRectangle = true;
            rectangleCheckBoxMenuItem.setSelected(true);
            drawNextEllipse = false;
            ellipseCheckBoxMenuItem.setSelected(false);
        } else {
            drawNextRectangle = !drawNextRectangle;
            mouseCheckBoxMenuItem.setSelected(true);
        }
//        System.out.println(drawNextLine + " " + drawNextRectangle + " " + drawNextEllipse);
    }//GEN-LAST:event_rectangleCheckBoxMenuItemActionPerformed

    private void ellipseCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ellipseCheckBoxMenuItemActionPerformed
        if (ellipseCheckBoxMenuItem.isSelected()) {
            mouseCheckBoxMenuItem.setSelected(false);
            drawNextLine = false;
            lineCheckBoxMenuItem.setSelected(false);
            drawNextRectangle = false;
            rectangleCheckBoxMenuItem.setSelected(false);
            drawNextEllipse = true;
            ellipseCheckBoxMenuItem.setSelected(true);
        } else {
            drawNextEllipse = !drawNextEllipse;
            mouseCheckBoxMenuItem.setSelected(true);
        }
//        System.out.println(drawNextLine + " " + drawNextRectangle + " " + drawNextEllipse);
    }//GEN-LAST:event_ellipseCheckBoxMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bringForwardMenuItem;
    private javax.swing.JMenuItem bringToFrontMenuItem;
    private javax.swing.JMenuItem clearMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private ui.DrawPanel drawPanel;
    private javax.swing.JMenu elementMenu;
    private javax.swing.JCheckBoxMenuItem ellipseCheckBoxMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fillColorMenuItem;
    private javax.swing.JMenuBar illustratorMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu layersMenu;
    private javax.swing.JCheckBoxMenuItem lineCheckBoxMenuItem;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JCheckBoxMenuItem mouseCheckBoxMenuItem;
    private javax.swing.JMenuItem outlineColorMenuItem;
    private javax.swing.JCheckBoxMenuItem rectangleCheckBoxMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem sendBackwardMenuItem;
    private javax.swing.JMenuItem sendToBackMenuItem;
    private javax.swing.JMenu shapesMenu;
    // End of variables declaration//GEN-END:variables
}
