/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package circlingcircles;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author ben
 */
public class DrawPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawPanel
     */
    Circle circle;
    
    public DrawPanel() {
        initComponents();
        setBackground(Color.WHITE);
    }
    
    public void setCircle(Circle c){
        this.circle = c;
    }
    
    public void clear(){
        circle.clear();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(circle != null){
            circle.setX(getWidth()/2);
            circle.setY(getHeight()/2);
            circle.setRadius(Math.min(getWidth(), getHeight())/4);
            circle.setChildCoords();
            
            circle.update();
            circle.draw(g);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
