
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author nicolas
 */
public class DrawPanel extends javax.swing.JPanel {
    
    private final int MAX_ITERATION = 1000;
    private ArrayList<Color> alColors = new ArrayList<>();
    private BufferedImage image = null;
    
    private double xMin = -2.00;
    private double xMax =  0.47;
    private double yMin = -1.12;
    private double yMax =  1.12;

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
        createPalette();
    }
    
    public void createPalette() {
        for (int i = 0; i < MAX_ITERATION; i++) {
            int rgb = Color.HSBtoRGB((float) i / MAX_ITERATION, 1f, 1f);
            Color color = new Color(rgb);
            alColors.add(color);
        }
        alColors.add(Color.BLACK);
    }
    
    public void createPalette2() {
        for (int i = 0; i < MAX_ITERATION; i++) {
            float t = (float) i / MAX_ITERATION;
            int r = (int) (t * 255);
            int g = (int) (t * t * 255);
            int b = 0;
            alColors.add(new Color(r, g, b));
        }
        alColors.add(Color.BLACK);
    }
    
    @Override
    public void paintComponent(Graphics g) {
        int width = getWidth();
        int height = getHeight();
        
        if (image == null || image.getWidth() != width || image.getHeight() != height) {
            image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            renderMandelBrot(image, width, height);
        }
        g.drawImage(image, 0, 0, null);
    }
    
    public void renderMandelBrot(BufferedImage imgage, int width, int height) {
        for (int px = 0; px < width; px++) {
            for (int py = 0; py < height; py++) {
                double x0 = xMin + px * (xMax - xMin) / width;
                double y0 = yMin + py * (yMax - yMin) / height;
                
                double x = 0.0;
                double y = 0.0;
                
                int iteration = 0;
                
                while (x*x + y*y <= 2*2 && iteration < MAX_ITERATION) {
                    double xTemp = x*x - y*y + x0;
                    y = 2*x*y + y0;
                    x = xTemp;
                    iteration++;
                }
                Color color = alColors.get(iteration);
                image.setRGB(px, py, color.getRGB());
            }
        }
    }
    
    public void scale(double factor, Point panelPoint) {
        int width = getWidth();
        int height = getHeight();
        if (width <= 0 || height <= 0) {
            return;
        }
        if (panelPoint == null) {
            panelPoint = new Point(width / 2, height / 2);
        }

        // current ranges
        double oldRangeX = xMax - xMin;
        double oldRangeY = yMax - yMin;

        // complex coordinate under the panel point
        double cX = xMin + panelPoint.x * oldRangeX / (width - 1.0);
        double cY = yMin + panelPoint.y * oldRangeY / (height - 1.0);

        // fractional position of the point inside the viewport [0..1]
        double rx = (cX - xMin) / oldRangeX;
        double ry = (cY - yMin) / oldRangeY;

        // new ranges after scaling. factor > 1 -> zoom in (smaller range)
        double newRangeX = oldRangeX / factor;
        double newRangeY = oldRangeY / factor;

        // safety limits (tweak as you like)
        final double MIN_RANGE = 1e-12;
        final double MAX_RANGE = 1e6;
        if (newRangeX < MIN_RANGE || newRangeY < MIN_RANGE) {
            return;
        }
        if (newRangeX > MAX_RANGE || newRangeY > MAX_RANGE) {
            return;
        }

        // compute new min/max so that cX/cY remain at the same fractional position rx/ry
        double newXMin = cX - rx * newRangeX;
        double newYMin = cY - ry * newRangeY;
        double newXMax = newXMin + newRangeX;
        double newYMax = newYMin + newRangeY;

        // apply new viewport
        xMin = newXMin;
        xMax = newXMax;
        yMin = newYMin;
        yMax = newYMax;

        // force re-render
        image = null;
    }
    
    // f(z) = z^2 + c

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
